version: "3.7"

services:
  html2pdf:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "6000:5000"
    restart: always
    networks:
      - global

networks:
  global:
    name: global_pi_network
    external: true
