version: "3.7"

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./src:/home/node/src
      - ./file.pdf:/home/node/file.pdf
    command: npm run server